import os
import re
import zipfile
import shutil
import requests
import html
import unicodedata
import logging
from urllib.parse import urlparse, parse_qs
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from bs4 import BeautifulSoup

from lncrawl.core.app import App
from lncrawl.core.sources import load_sources

logger = logging.getLogger(__name__)

# --- PURE REQUESTS CONNECTION POOL ---
SHARED_SESSION = requests.Session()
SHARED_SESSION.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36",
    "Accept-Language": "en-US,en;q=0.9",
})

_old_session_request = requests.Session.request
def _new_session_request(self, method, url, **kwargs):
    if kwargs.get('timeout') is None:
        kwargs['timeout'] = 20.0
    return _old_session_request(self, method, url, **kwargs)
requests.Session.request = _new_session_request

adapter = HTTPAdapter(pool_connections=20, pool_maxsize=20, max_retries=1)
SHARED_SESSION.mount('http://', adapter)
SHARED_SESSION.mount('https://', adapter)
# -------------------------------------

def apply_fanmtl_patch():
    try:
        from lncrawl.sources.en.f.fanmtl import FanMTLCrawler
        if getattr(FanMTLCrawler, '_is_healer_patched', False):
            return

        def custom_read_novel_info(self):
            soup = self.get_soup(self.novel_url)
            possible_title = soup.select_one("h1.novel-title")
            self.novel_title = possible_title.text.strip() if possible_title else "Unknown"

            img_tag = soup.select_one("figure.cover img") or soup.select_one(".fixed-img img")
            if img_tag:
                url = img_tag.get("src")
                if "placeholder" in str(url) and img_tag.get("data-src"):
                    url = img_tag.get("data-src")
                self.novel_cover = self.absolute_url(url)

            author_tag = soup.select_one('.novel-info .author span[itemprop="author"]')
            self.novel_author = author_tag.text.strip() if author_tag else "Unknown"

            summary_div = soup.select_one(".summary .content")
            self.novel_synopsis = summary_div.get_text("\n\n").strip() if summary_div else ""

            self.volumes = [{"id": 1, "title": "Volume 1"}]
            self.chapters = []

            self.parse_chapter_list(soup)

            pagination_links = soup.select('.pagination a[data-ajax-update="#chpagedlist"]')
            if pagination_links:
                last_page = pagination_links[-1]
                href = last_page.get("href")
                common_url = self.absolute_url(href).split("?")[0]
                query = parse_qs(urlparse(href).query)
                
                page_params = query.get("page", ["0"])
                page_count = int(page_params[0]) + 1
                wjm = query.get("wjm", [""])[0] if "wjm" in query else ""

                # 🚨 STRICTLY SYNCHRONOUS. NO FUTURES. NO RACE CONDITIONS. 🚨
                for page in range(1, page_count):
                    try:
                        url = f"{common_url}?page={page}&wjm={wjm}"
                        page_soup = self.get_soup(url)
                        self.parse_chapter_list(page_soup)
                    except Exception as e:
                        logger.error(f"Failed to fetch page {page}: {e}")

        FanMTLCrawler.read_novel_info = custom_read_novel_info
        FanMTLCrawler._is_healer_patched = True
    except ImportError:
        pass

def strip_watermark(extract_dir):
    """Surgically removes the 'Generated by Lightnovel Crawler' watermark while preserving the Source URL."""
    intro_path = next((os.path.join(r, f) for r, _, fs in os.walk(extract_dir) for f in fs if f == "intro.xhtml"), None)
    if intro_path:
        try:
            with open(intro_path, 'r', encoding='utf-8') as f:
                soup = BeautifulSoup(f.read(), 'html.parser')
            
            # Find the <i> tag containing the watermark
            for i_tag in soup.find_all('i'):
                if 'Generated by' in i_tag.text and 'Lightnovel Crawler' in i_tag.text:
                    # Remove the <br> right before it for clean formatting
                    prev = i_tag.find_previous_sibling()
                    if prev and prev.name == 'br':
                        prev.decompose()
                    i_tag.decompose()
                    break
                    
            with open(intro_path, 'w', encoding='utf-8') as f:
                f.write(str(soup))
        except Exception as e:
            logger.error(f"Failed to strip watermark: {e}")

def post_process_redownload(epub_path):
    """Intercepts redownloaded EPUBs to strip watermarks and strictly enforce mimetype standard."""
    extract_dir = epub_path + "_post_unzipped"
    os.makedirs(extract_dir, exist_ok=True)
    try:
        with zipfile.ZipFile(epub_path, 'r') as zip_ref:
            zip_ref.extractall(extract_dir)
            
        strip_watermark(extract_dir)
        
        fixed_epub_path = epub_path.replace('.epub', '_cleaned.epub')
        with zipfile.ZipFile(fixed_epub_path, 'w') as zipf:
            mimetype_path = os.path.join(extract_dir, 'mimetype')
            if os.path.exists(mimetype_path):
                zipf.write(mimetype_path, 'mimetype', compress_type=zipfile.ZIP_STORED)
            for r, _, fs in os.walk(extract_dir):
                for file in fs:
                    if file == 'mimetype' and r == extract_dir: continue
                    abs_path = os.path.join(r, file)
                    zipf.write(abs_path, os.path.relpath(abs_path, extract_dir), compress_type=zipfile.ZIP_DEFLATED)
                    
        shutil.rmtree(extract_dir, ignore_errors=True)
        shutil.move(fixed_epub_path, epub_path)
    except Exception as e:
        logger.error(f"Post-process error on redownload: {e}")
        shutil.rmtree(extract_dir, ignore_errors=True)

def clean_text(text):
    if not text: return ""
    decoded = html.unescape(str(text))
    normalized = unicodedata.normalize('NFKD', decoded)
    alphanumeric = re.sub(r'[^a-zA-Z0-9\s]', '', normalized)
    return " ".join(alphanumeric.lower().split())

def extract_url_from_epub(epub_path):
    extract_dir = epub_path + "_unzipped"
    os.makedirs(extract_dir, exist_ok=True)
    
    try:
        with zipfile.ZipFile(epub_path, 'r') as zip_ref:
            zip_ref.extractall(extract_dir)
    except zipfile.BadZipFile:
        shutil.rmtree(extract_dir, ignore_errors=True)
        return None, extract_dir, "Bad Zip File (Likely 0 bytes / Interrupted download)"
    except Exception as e:
        shutil.rmtree(extract_dir, ignore_errors=True)
        return None, extract_dir, f"Zip Extraction Crash: {str(e)}"

    intro_path = next((os.path.join(r, f) for r, _, fs in os.walk(extract_dir) for f in fs if f == "intro.xhtml"), None)
    if not intro_path:
        shutil.rmtree(extract_dir, ignore_errors=True)
        return None, extract_dir, "No intro.xhtml found"

    with open(intro_path, 'r', encoding='utf-8') as f:
        match = re.search(r'Source:</b>\s*<a href="([^"]+)">', f.read())
        
    if not match:
        shutil.rmtree(extract_dir, ignore_errors=True)
        return None, extract_dir, "Source URL not found inside EPUB"
        
    return match.group(1), extract_dir, None

def fetch_live_toc(url):
    apply_fanmtl_patch()
    app = App()
    try:
        app.user_input = url
        app.prepare_search() 
        if app.crawler: app.crawler.scraper = SHARED_SESSION
        app.get_novel_info()
        
        canonical_toc = {}
        has_duplicates = False
        
        for idx, chap in enumerate(app.crawler.chapters):
            chap_title = chap.get('title', '') if isinstance(chap, dict) else getattr(chap, 'title', '')
            cleaned = clean_text(chap_title)
            
            if cleaned:
                if cleaned in canonical_toc: has_duplicates = True
                canonical_toc[cleaned] = idx
                
        return canonical_toc, has_duplicates, None
    except Exception as e:
        return None, False, str(e)
    finally:
        app.destroy()

def extract_title_from_html(html_path):
    with open(html_path, 'r', encoding='utf-8') as f:
        soup = BeautifulSoup(f.read(), 'html.parser')
    title_tag = soup.find('title')
    return title_tag.text if title_tag else ""

def fix_epub_spine(epub_path, extract_dir, canonical_toc, log_data):
    epub_chapters = [f for r, _, fs in os.walk(extract_dir) for f in fs if f.startswith("chapter_") and f.endswith(".xhtml")]

    if len(epub_chapters) < len(canonical_toc):
        shutil.rmtree(extract_dir, ignore_errors=True)
        log_data.append("❌ Missing chapters detected in EPUB compared to live source.")
        return "REDOWNLOAD", None

    file_to_true_index = {}
    seen_epub_titles = set()
    
    for chap_file in epub_chapters:
        abs_chap_path = next((os.path.join(r, chap_file) for r, _, fs in os.walk(extract_dir) if chap_file in fs), None)
        raw_title = extract_title_from_html(abs_chap_path)
        cleaned_title = clean_text(raw_title)
        
        if cleaned_title in seen_epub_titles:
            shutil.rmtree(extract_dir, ignore_errors=True)
            log_data.append(f"⚠️ Duplicate title found inside EPUB: '{raw_title}'. Cannot safely sort.")
            return "REDOWNLOAD", None
        seen_epub_titles.add(cleaned_title)
        
        if cleaned_title in canonical_toc:
            file_to_true_index[chap_file] = canonical_toc[cleaned_title]
        else:
            shutil.rmtree(extract_dir, ignore_errors=True)
            log_data.append(f"⚠️ Exact title '{raw_title}' not found in live source TOC.")
            return "REDOWNLOAD", None

    # --- 0. CLEAN WATERMARKS ---
    strip_watermark(extract_dir)

    # --- 1. REORDER OPF SPINE ---
    opf_path = next((os.path.join(r, f) for r, _, fs in os.walk(extract_dir) for f in fs if f.endswith(".opf")), None)
    with open(opf_path, 'r', encoding='utf-8') as f:
        opf_soup = BeautifulSoup(f.read(), 'xml')
        
    manifest = opf_soup.find('manifest')
    id_to_href = {item.get('id'): item.get('href') for item in manifest.find_all('item') if item.get('id')}

    spine = opf_soup.find('spine')
    itemrefs = spine.find_all('itemref')
    original_idrefs = [item.get('idref') for item in itemrefs]
    
    def spine_sort(tag):
        idref = tag.get('idref')
        if not idref: return 999999
        href = id_to_href.get(idref)
        if href:
            # Safely cross-references the actual filename, stopping intro.xhtml from dropping to 999999
            basename = os.path.basename(href.split('#')[0])
            if basename in file_to_true_index: return file_to_true_index[basename]
            if basename.startswith('volume_'): return -1000
            if basename in ['cover.xhtml', 'intro.xhtml', 'nav.xhtml', 'front.xhtml']: return -2000
        return 999999

    sorted_itemrefs = sorted(itemrefs, key=spine_sort)
    sorted_idrefs = [item.get('idref') for item in sorted_itemrefs]
    is_order_changed = (original_idrefs != sorted_idrefs)

    spine.clear()
    for item in sorted_itemrefs: spine.append(item)
    with open(opf_path, 'w', encoding='utf-8') as f:
        f.write(str(opf_soup))

    # --- 2. REORDER NCX ---
    ncx_path = next((os.path.join(r, f) for r, _, fs in os.walk(extract_dir) for f in fs if f.endswith(".ncx")), None)
    if ncx_path:
        with open(ncx_path, 'r', encoding='utf-8') as f:
            ncx_soup = BeautifulSoup(f.read(), 'xml')
        
        navmap = ncx_soup.find('navMap')
        if navmap:
            def sort_ncx_recursive(container):
                navpoints = container.find_all('navPoint', recursive=False)
                if not navpoints: return
                for np in navpoints: sort_ncx_recursive(np)
                    
                def get_idx(np):
                    content = np.find('content')
                    if content:
                        src = content.get('src', '')
                        basename = os.path.basename(src.split('#')[0])
                        if basename in file_to_true_index: return file_to_true_index[basename]
                        if basename.startswith('volume_'): return -1000
                        if basename in ['cover.xhtml', 'intro.xhtml', 'nav.xhtml', 'front.xhtml']: return -2000
                    return 999999
                    
                sorted_nps = sorted(navpoints, key=get_idx)
                for np in navpoints: np.extract()
                for np in sorted_nps: container.append(np)

            sort_ncx_recursive(navmap)
            
            for i, np in enumerate(ncx_soup.find_all('navPoint')):
                np['playOrder'] = str(i + 1)
                
            with open(ncx_path, 'w', encoding='utf-8') as f:
                f.write(str(ncx_soup))

    # --- 3. REORDER TOC.XHTML ---
    toc_xhtml = next((os.path.join(r, f) for r, _, fs in os.walk(extract_dir) for f in fs if f in ["toc.xhtml", "nav.xhtml"]), None)
    if toc_xhtml:
        with open(toc_xhtml, 'r', encoding='utf-8') as f:
            toc_soup = BeautifulSoup(f.read(), 'html.parser')
        
        nav_list = toc_soup.find(['ol', 'ul'])
        if nav_list:
            def sort_html_recursive(container):
                items = container.find_all('li', recursive=False)
                if not items: return
                
                for li in items:
                    child_list = li.find(['ol', 'ul'], recursive=False)
                    if child_list: sort_html_recursive(child_list)
                        
                def get_idx(li):
                    a_tag = li.find('a', recursive=False) or li.find('a')
                    if a_tag:
                        href = a_tag.get('href', '')
                        basename = os.path.basename(href.split('#')[0])
                        if basename in file_to_true_index: return file_to_true_index[basename]
                        if basename.startswith('volume_'): return -1000
                        if basename in ['cover.xhtml', 'intro.xhtml', 'nav.xhtml', 'front.xhtml']: return -2000
                    return 999999
                    
                sorted_items = sorted(items, key=get_idx)
                for li in items: li.extract()
                for li in sorted_items: container.append(li)

            sort_html_recursive(nav_list)
            with open(toc_xhtml, 'w', encoding='utf-8') as f:
                f.write(str(toc_soup))
        
    fixed_epub_path = epub_path.replace('.epub', '_fixed.epub')
    with zipfile.ZipFile(fixed_epub_path, 'w') as zipf:
        mimetype_path = os.path.join(extract_dir, 'mimetype')
        if os.path.exists(mimetype_path):
            zipf.write(mimetype_path, 'mimetype', compress_type=zipfile.ZIP_STORED)
            
        for r, _, fs in os.walk(extract_dir):
            for file in fs:
                if file == 'mimetype' and r == extract_dir: continue 
                abs_path = os.path.join(r, file)
                zipf.write(abs_path, os.path.relpath(abs_path, extract_dir), compress_type=zipfile.ZIP_DEFLATED)
                
    shutil.rmtree(extract_dir, ignore_errors=True)
    
    if is_order_changed:
        log_data.append(f"🛠️ Successfully mapped {len(epub_chapters)} chapters word-for-word. All Spines and TOCs deeply rewritten.")
        return "FIXED", fixed_epub_path
    else:
        log_data.append("✅ EPUB order was already perfect. Removed watermark and strictly rebuilt.")
        return "OK", fixed_epub_path

def redownload_worker(url, out_dir):
    apply_fanmtl_patch()
    load_sources()
    app = App()
    try:
        app.user_input = url
        app.output_path = out_dir
        app.pack_by_volume = False
        app.output_formats = {'epub': True}
        app.prepare_search()
        app.get_novel_info()
        for _ in app.start_download(): pass
        for fmt, f in app.bind_books():
            post_process_redownload(f)
            return f
        return None
    except Exception as e:
        return None
    finally:
        app.destroy()